services:
  mongodb:
    image: mongo:4.4.26
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'root'
      MONGO_INITDB_ROOT_PASSWORD: 'changeme'
      MONGO_INITDB_DATABASE: 'api'
    networks:
      - java-microservices-spring-api

  mongo-express:
    image: mongo-express:latest
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: 'root'
      ME_CONFIG_MONGODB_ADMINPASSWORD: 'changeme'
      ME_CONFIG_MONGODB_SERVER: 'mongodb'
    networks:
      - java-microservices-spring-api

  consul-server:
    image: consul:1.15.4
    ports:
      - "8500:8500"
      - "8600:8600/udp"
    environment:
      - CONSUL_BIND_INTERFACE=eth0
      - CONSUL_CLIENT_INTERFACE=eth0
      - CONSUL_SERVER=true
    command: "agent -server -bootstrap-expect=1 -ui -client=0.0.0.0"
    networks:
      - java-microservices-spring-api

  consul-client:
    image: consul:1.15.4
    ports:
      - "8501:8500"
      - "8601:8600/udp"
    environment:
      - CONSUL_BIND_INTERFACE=eth0
      - CONSUL_CLIENT_INTERFACE=eth0
      - CONSUL_SERVER=false
    command: "agent -ui -client=0.0.0.0 -retry-join=consul-server"
    networks:
      - java-microservices-spring-api


  api:
    image: java-microservices-spring-api:latest
    ports:
      - "9001:9001"
    depends_on:
      - mongodb
    networks:
      - java-microservices-spring-api

  gateway:
    image: java-microservices-spring-gateway:latest
    ports:
      - "9100:9100"
    depends_on:
      - api
    networks:
      - java-microservices-spring-api

networks:
  java-microservices-spring-api:
    # noinspection ComposeUnknownKeys
    name: java-microservices-spring-api
    driver: bridge
